// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlgaddeyawmfprzfytyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZ2FkZGV5YXdtZnByemZ5dHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDg1OTEsImV4cCI6MjA3MzkyNDU5MX0.Qulr_UYjwlsHIzSYSeOX444jkI8UxYSocvC89Nqk6pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});